"""create user and blog table migrations

Revision ID: c216a7d26014
Revises:
Create Date: 2023-08-05 00:52:11.188144

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c216a7d26014"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
